# Generated by Django 4.0.2 on 2022-02-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.CharField(choices=[('Fazendo', 'Doing'), ('Feito', 'Done')], max_length=10),
        ),
    ]
