# Generated by Django 4.0.2 on 2022-02-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.CharField(choices=[('Fazendo', 'Fazendo'), ('Feito', 'Feito')], max_length=10),
        ),
    ]
